# Generated by Django 3.0.5 on 2020-04-07 16:24

from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('img_1', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('img_2', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('img_3', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('img_4', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
