# Generated by Django 3.0.5 on 2020-04-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('img_1', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('img_2', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('img_3', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('img_4', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('img_5', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('img_6', models.ImageField(blank=True, upload_to='photo/%y/%m/%d/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(blank=True, max_length=20)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.Gallery')),
                ('servicelist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.ServiceList')),
            ],
        ),
        migrations.AddField(
            model_name='gallery',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.Location'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.Gallery')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.InfoTable')),
            ],
        ),
    ]
