# Generated by Django 3.0.5 on 2020-04-07 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_auto_20200407_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(blank=True, max_length=20)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.Gallery')),
                ('servicelist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.ServiceList')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(blank=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.Gallery')),
            ],
        ),
    ]
