# Generated by Django 3.0.5 on 2020-04-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_feedback_servicelist_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='img_5',
            field=models.ImageField(blank=True, upload_to='photo/%y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='img_6',
            field=models.ImageField(blank=True, upload_to='photo/%y/%m/%d/'),
        ),
    ]
