# Generated by Django 3.0.5 on 2020-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20200411_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='rent_per_day',
            field=models.IntegerField(default=0),
        ),
    ]
