ServiceList = {
    1 : 'Curating/exhibition design and set up',
    2 : 'Photo printing',
	3 : 'Photo framing',
	4 : 'Panel board hire for outdoor exhibitions',
	5 : 'Couriering/Emailing Invitation cards',
	6 : 'Arranging Press Conference',
	7 : 'Video projection facility',
	8 : 'Digitization',
	9 : 'Poster',
	10 : 'Brochure',
	11 : 'Invitation cards',
	12 : 'Press kit: press release print and soft, image in cd pen, folder writing pad',
	13 : 'Banner, backdrop',
	14 : 'Festoon',
	15 : 'Posting in Facebook/ Twitter',
	16 : 'Merchandising',
	17 : 'Sitting arrangement (pandal, dais, podium etc)',
	18 : 'Public address system; Flower bouquet, water, tissue for dais, ribbon',
	19 : 'Refreshment',
	20 : 'Projection: Projector, computer, screen etc.',
	21 : 'Live streaming on internet',
	22 : 'Photo documentation and Video documentation'
}