# Generated by Django 3.0.5 on 2020-04-09 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.IntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payment', models.BooleanField(default=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.Gallery')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payment.Rent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.InfoTable')),
            ],
        ),
    ]
