# Generated by Django 3.0.5 on 2020-04-10 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_delete_user'),
        ('payment', '0002_auto_20200410_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.UserInfo'),
        ),
    ]
