# Generated by Django 3.0.5 on 2020-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200411_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='rent',
        ),
        migrations.AddField(
            model_name='payment',
            name='total_pay',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Rent',
        ),
    ]
