# Generated by Django 3.0.5 on 2020-04-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_payment_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
    ]
