# Generated by Django 3.0.5 on 2020-04-14 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_auto_20200413_1209'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0010_auto_20200414_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
