# Generated by Django 3.0.5 on 2020-04-09 21:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('galleries', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exebition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exebitionType', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(default=0, null=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('TimeSlot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.TimeSlot')),
                ('exebition', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.Exebition')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='galleries.Gallery')),
                ('userinfo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.InfoTable')),
            ],
        ),
    ]
