# Generated by Django 3.0.5 on 2020-04-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userinfo'),
        ('booking', '0002_auto_20200410_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.UserInfo'),
        ),
    ]
