# Generated by Django 3.0.5 on 2020-04-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200411_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='time',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='timeed',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='timest',
            field=models.TimeField(null=True),
        ),
    ]
