# Generated by Django 3.0.5 on 2020-04-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200411_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='timest',
            field=models.TextField(null=True),
        ),
    ]
