# Generated by Django 3.0.5 on 2020-04-13 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0007_auto_20200413_1209'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0007_auto_20200412_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='TimeSlot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.TimeSlot'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='exebition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Exebition'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galleries.Gallery'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='userinfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
