# Generated by Django 3.0.5 on 2020-04-13 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20200413_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
