# Generated by Django 3.0.5 on 2020-04-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20200413_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='timest',
            field=models.TimeField(null=True),
        ),
    ]
