# Generated by Django 3.0.5 on 2020-04-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infotable',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
