# Generated by Django 3.0.5 on 2020-04-10 11:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200410_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='abc@email.com', max_length=255, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('staf', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
    ]
