# Generated by Django 3.0.5 on 2020-04-10 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staf',
            new_name='staff',
        ),
    ]
