# Generated by Django 3.0.5 on 2020-04-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_auto_20200410_2256'),
        ('booking', '0002_auto_20200410_2256'),
        ('payment', '0002_auto_20200410_2256'),
        ('user', '0006_infotable_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoTable',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
