# Generated by Django 3.0.5 on 2020-04-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20200411_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='passsowrd',
            new_name='password',
        ),
    ]
