# Generated by Django 3.0.5 on 2020-04-10 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200411_0137'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userinfo',
            managers=[
            ],
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table=None,
        ),
    ]
