# Generated by Django 3.0.5 on 2020-04-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20200411_0150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
