# Generated by Django 3.0.5 on 2020-04-10 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200411_0307'),
        ('booking', '0004_auto_20200411_0307'),
        ('galleries', '0004_auto_20200411_0307'),
        ('user', '0014_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
