# Generated by Django 3.0.5 on 2020-04-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blogpost',
            field=models.TextField(null=True),
        ),
    ]
