# Generated by Django 3.0.5 on 2020-04-12 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_profile_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='blogpost',
        ),
    ]
